config/routes.rb
Spree::Core::Engine.routes.draw do

	namespace :admin do

    resource :postmaster_settings, :only => ['show', 'update', 'edit']

    get 'orders/:order_id/label/:shipment_id', :to => "orders#label", :as => :shipping_label
  end
  
end

app/controllers/spree/admin/orders_controller_decorator.rb
require 'postmaster'

Spree::Admin::OrdersController.class_eval do
	
  def label
    begin
    	generate_label(params[:shipment_id])
    	flash[:notice] = "Label successfully generated"
    rescue Exception => e
      flash[:error] = e.message
    end
    redirect_to :back
  end

  private

  def clean_phone_number(number)
    number.gsub(/\+|\.|\-|\(|\)|\s/, '')
  end

  def generate_label(shipment_id)

		Postmaster.api_key = Spree::Postmaster::Config[:api_key]

    shipment = Spree::Shipment.find_by_number(shipment_id)
    stock_location = shipment.stock_location
    order = shipment.order
		shipping_method = shipment.shipping_method
		default_weight = Spree::Postmaster::Config[:default_weight]

		# use shipment.inventory units and not shipment.line_items so that this works w/product-assembly extension too
    weight_in_ounces = shipment.inventory_units.sum do |i|
     	w = i.variant.weight
     	if w.blank? or w <= 0     		
     		w = default_weight 
     	end
     	w
    end
    weight_in_pounds = weight_in_ounces / 16.0

    # prepare the customs declariation form / commercial invoice if destination country different from from country
    customs = nil
    if Spree::Country.find(order.ship_address.country_id).iso != Spree::Postmaster::Config[:country]
    	customs = {
    		type: "Other",
    		contents: [{
					description: "Personal Items",
					country_of_origin: Spree::Postmaster::Config[:country],
					quantity: 1,
					value: ((!order.item_total.blank? && order.item_total > 1) ? order.item_total : 1),		# total after adjustments and before taxes & shipping if available and greater than 1, otherwise declare $1
					weight: weight_in_ounces * 0.9, 		# has to be lower than total package weight in ounces 
					weight_units: 'OZ'
    		}]
    	}
		end

		# when user will choose delivery type you create shipment
		result = Postmaster::Shipment.create(
		  :from => {
		    :company => Spree::Postmaster::Config[:company],
		    :contact => Spree::Postmaster::Config[:contact],
		    :line1 => Spree::Postmaster::Config[:address],
		    :city => Spree::Postmaster::Config[:city],
		    :state => Spree::Postmaster::Config[:state],
		    :zip_code => Spree::Postmaster::Config[:zip_code],
		    :phone_no => Spree::Postmaster::Config[:phone_number],
		    :country => Spree::Postmaster::Config[:country]
		  },
		  :to => {
		  	:company => order.ship_address.company,
		    :contact => "#{order.ship_address.firstname} #{order.ship_address.lastname}",
		    :line1 => order.ship_address.address1,
		    :line2 => order.ship_address.address2 || '',
		    :city => order.ship_address.city,
		    :state => order.ship_address.state_name || (order.ship_address.state.nil? ? "" : order.ship_address.state.abbr),
		    :zip_code => order.ship_address.zipcode.gsub(/\-|\s/, ''),
		    :phone_no => clean_phone_number(order.ship_address.phone == "(not given)" ? order.bill_address.phone : order.ship_address.phone),
		    :country => Spree::Country.find(order.ship_address.country_id).iso
		  },
		  :carrier => "usps",
		  :service => shipping_method.admin_name, # the internal name of each shipping method must match a valid postmaster.io service level, e.g.: 2DAY
		  :package => {
		    :value => order.item_total,
		    :weight => weight_in_pounds,
		    :length => nil || Spree::Postmaster::Config[:default_length],
		    :width => nil || Spree::Postmaster::Config[:default_width],
		    :height => nil || Spree::Postmaster::Config[:default_height],
		    :customs => customs
		  },
		  :reference => "Order ##{order.id}"
		)
		
		# result.inspect example:
		# <Postmaster::Shipment:0x3fd7cf8555d4 id=5649050225344512> JSON: 
		# {"id":5649050225...,
		# "status":"Processing",
		# "tracking":["949990712345..."],
		# "cost":530,
		# "prepaid":true,
		# "service":"2DAY",
		# "package_count":1,
		# "created_at":1393523684,
		# "saturday":false,
		# "to":[["city","Austin"],["country","US"],["phone_no","512..."],["line1","123 ..."],["state","TX"],["contact","..."],["residential",true],["zip_code","78701"]],
		# "carrier":"usps",
		# "from":[["city","Austin"],["country","US"],["company","BlushBox, Inc."],["phone_no","512..."],["line1","101 Test Addy"],["state","TX"],["residential",true],["zip_code","78701"]],
		# "packages":[[["weight_units","LB"],["weight",1.0],["type","CUSTOM"],["value","174.0"],["height",4],["width",3],["length",2],
		# ["label_url","/v1/label/AMIfv97VnI7GRonSbx-1234...."],
		# ["dimension_units","IN"]]],"additional_data":{}}

		# store postmaster.io id, label url, and tracking #
		shipment.postmaster_id = result.id
		shipment.postmaster_label_url = result.packages.first.label_url
		shipment.tracking = result.tracking.first
		shipment.save!

		# # anytime you can extract shipment data
		# shipment = Postmaster::Shipment.retrieve(shipment_id)
		# #puts shipment.inspect

		# # or check delivery status
		# result = shipment.track()
		# #puts result.inspect

		# # you can cancel shipment, but only before being picked up by the carrier
		# result = shipment.void()
		# #puts result.inspect

	end
end

app/controllers/spree/admin/postmaster_settings_controller.rb
class Spree::Admin::PostmasterSettingsController < Spree::Admin::BaseController

  def edit
    @preferences_Postmaster = [:api_key, :default_weight, :default_length, :default_width, :default_height]
    @preferences_FromAddress = [:company, :contact, :address, :city, :state, :zip_code, :phone_number, :country]

    @config = Spree::PostmasterConfiguration.new
  end

  def update
    config = Spree::PostmasterConfiguration.new

    params.each do |name, value|
      next unless config.has_preference? name
      config[name] = value
    end

    redirect_to edit_admin_postmaster_settings_path
  end

end

app/views/spree/admin/orders/_label.html.erb
<% if shipment.postmaster_label_url.empty? -%>
	<%= link_to :label, admin_shipping_label_path(@order.number,shipment.number), :class => 'ship button icon-upload' %> -
<% else -%>
	<%= link_to :label, 'http://postmaster.io/' + shipment.postmaster_label_url, :class => 'ship button icon-print' %> -
<% end -%>

app/views/spree/admin/postmaster_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:postmaster_settings) %>
<% end %>

<%= form_tag admin_postmaster_settings_path, :method => :put  do |form| %>
  <div id="preferences" data-hook>
    <fieldset class="general no-border-top">
      <div class="row">
        <div class="alpha six columns">
          <fieldset class="security no-border-bottom">
            <legend align="center"><%= Spree.t(:postmaster_settings)%></legend>
            <% @preferences_Postmaster.each do |key|
                type = @config.preference_type(key) %>
                <div class="field">
                  <%= label_tag(key, Spree.t(key) + ': ') + tag(:br) if type != :boolean %>
                  <%= preference_field_tag(key, @config[key], :type => type) %>
                  <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
                </div>
            <% end %>
          </fieldset>
        </div>
      </div>

      <div class="row">
        <div class="alpha six columns">
          <fieldset class="currency no-border-bottom">
            <legend align="center"><%= Spree.t(:from_address_settings)%></legend>
            <% @preferences_FromAddress.each do |key|
                type = @config.preference_type(key) %>
                <div class="field">
                  <%= label_tag(key, Spree.t(key) + ': ') + tag(:br) if type != :boolean %>
                  <%= preference_field_tag(key, @config[key], :type => type) %>
                  <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
                </div>
            <% end %>
          </fieldset>
        </div>
      </div>

      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t(:update), 'icon-refresh' %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= link_to_with_icon 'icon-remove', Spree.t(:cancel), edit_admin_postmaster_settings_url, :class => 'button' %>
      </div>

    </fieldset>
  </div>
<% end %>